version: 2

sources:
  - name: raw_data  # Matches stg_telegram_messages.sql
    schema: public  # Assuming your tables are in the public schema
    tables:
      - name: telegram_messages

  - name: public    # Matches stg_yolo_detections.sql
    tables:
      - name: raw_yolo_detections